version: 2.1
jobs:
  test-cases:
    docker:
      - image: kingalt/go-gcc:1.1
    steps:
      - checkout
      - run:
          name: run the test cases
          command: 'go test -cover -coverprofile=c.out'
      - run:
          name: Generate the test cases
          command: 'go tool cover -html=c.out -o coverage.html'
      - run:
          name: send test case to sonarcloud
          command: 'go tool cover -html=c.out -o coverage.html'
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-cases
