version: 2.1
jobs:
  test-cases:
    docker:
      - image: golang:1.12.1-alpine3.9
    steps:
      - checkout
      - run:
          name: run the test cases
          command: 'go test -cover -coverprofile=c.out'
      - run:
          name: Generate the test cases
          command: 'go tool cover -html=c.out -o coverage.html'
      - run:
          name: Run Build
          command: 'ng build'
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-cases
